Porting //eve/staging/2019-CENTAUR->//eve/development/MAINLINE at head (1465722) - using branchspec //eve/staging/2019-CENTAUR->//eve/development/MAINLINE
========================================

Change 1465150 by bara@eve_branches_staging_2019-CENTAUR_bara-pc on 2019/02/26 13:14:13

cluError: moduleButtonTooltip.py(198) UpdateToolTips - 'float' object has no attribute 'repairTimeLeft'
https://jira.ccpgames.com/browse/EVEDEV-7105

 - fallout from CL 1451498, where I missed changing the moduleDamageInfo for drones
 - fixing it by letting the drone code return keyval

========================================

Change 1465232 by bara@eve_branches_staging_2019-CENTAUR_bara-pc on 2019/02/26 13:52:48

Manual control to navigate ships not working
https://jira.ccpgames.com/browse/EVEDEV-7113

 - this was happening because flightControls is listening to events, but that service is never started (after CL 1454793), so it's not listening
 - changing it so we start the service

========================================

Change 1465270 by joshua@joshua-ws on 2019/02/26 14:22:30

Republishing for decal errors

https://jira.ccpgames.com/browse/GFX-4954

========================================

Change 1465289 by gregor@eve_branches_staging_2019-CENTAUR_gregor-pc on 2019/02/26 14:44:10

Removing marketability of placeholder types

https://jira.ccpgames.com/browse/TQ-131430

========================================

Change 1465603 by hinrikg@eve_branches_staging_2019-CENTAUR_hinrikg-ws on 2019/02/27 10:43:43

As a player when I drag or double-click a missing skill to the queue I am notified that I need to purchase it
https://jira.ccpgames.com/browse/GEN-1985

Show overlay when skills you don't own are dragged to the queue. You can choose to either buy the skill if it's available (otherwise view market details) or cancel. If the queue is changed while the overlay is displayed then we close the overlay.

========================================

Change 1465622 by paulina@PAULINA-WS on 2019/02/27 10:58:57

Republish of Deimos for logo fix 

https://jira.ccpgames.com/browse/TQ-131493

========================================

Change 1465636 by eric@eric_MAINLINE_FOR_REAL on 2019/02/27 11:02:39

[eve 2019-CENTAUR][Audio] Add audio event debugger in for QA.

Review: http://codecollaborator/ui#review:id=17338

========================================

Change 1465642 by olafurth@eve_branches_staging_2019-CENTAUR_olafurth-ws on 2019/02/27 11:06:16

Fixing broken bindings for auroras on planets

https://jira.ccpgames.com/browse/EVEDEV-7096
https://jira.ccpgames.com/browse/EVEDEV-7057

========================================

Change 1465679 by hinrikg@eve_branches_staging_2019-CENTAUR_hinrikg-ws on 2019/02/27 11:34:11

As a player when I drag or double-click a missing skill to the queue I am notified that I need to purchase it
https://jira.ccpgames.com/browse/GEN-1985

Double clicking a skill in the character sheet no longer shows information on skills that are missing. Instead it shows the missing skill overlay in the skill queue panel.

========================================

Change 1465682 by olafurth@eve_branches_staging_2019-CENTAUR_olafurth-ws on 2019/02/27 11:36:07

Fixing the graphicsreport that I broke accidentally
https://jira.ccpgames.com/browse/EVEDEV-7057

========================================

Change 1465722 by olafurth@eve_branches_staging_2019-CENTAUR_olafurth-ws on 2019/02/27 12:06:40

Fixing planet rings and atmosphere
https://jira.ccpgames.com/browse/EVEDEV-7095
https://jira.ccpgames.com/browse/EVEDEV-7085

[git-p4: depot-paths = "//eve/branches/development/MAINLINE/carbon/src/Trinity/": change = 1465761]