Porting //eve/staging/2019-INCUBUS->//eve/development/MAINLINE at head (1578478) - using branchspec //eve/staging/2019-INCUBUS->//eve/development/MAINLINE
========================================

Change 1573768 by javier@EVE_DEVELOPMENT_JAVIER-WS on 2019/09/24 13:57:24

Removing moon file as it was renamed https://jira.ccpgames.com/browse/TC-44

========================================

Change 1576801 by hjaltil@eve_branches_staging_2019-INCUBUS_hjaltil-pc on 2019/09/30 13:54:45

NPE: Claim Rewards button is inoperable during warp https://jira.ccpgames.com/browse/EVEDEV-8456

* Added CLAIM_REWARDS button state so the button won't think it's in a different state than it is.
* The button was told it was in the WARP_TO state but then overridden to show "Claim Rewards" as its label.

========================================

Change 1576837 by hrafng@eve_branches_staging_2019-INCUBUS_hrafn-pc on 2019/09/30 14:17:11

Authored collision geometry on the TriGlavian Observatory tgo01_t1 is not visible in game https://jira.ccpgames.com/browse/EVEDEV-8462

1. Adding the destructible effect beacon group to the list of groups that can have miniballs/miniboxes/minicapsules etc.

2. Have the stellar observatory collidable structure face towards the sun upon adding it to the park.

========================================

Change 1576873 by hjaltil@eve_branches_staging_2019-INCUBUS_hjaltil-pc on 2019/09/30 14:35:05

Agency: Undock button does not change to Abort Undock https://jira.ccpgames.com/browse/EVEDEV-8467

* Added logic for content pieces to check if the player is undocking, and showing the appropriate button state.

========================================

Change 1576909 by asgeir.arnason@ASGEIR-WS on 2019/09/30 14:59:36

As a new player, I want the instructions Aura gives me to be split into separate tasks whenever possible 
https://jira.ccpgames.com/browse/PSYCHO-2107 
-Added a 'warp to' task to the operation Measuring the threat
-Edited the conversation text on the following tasks to more clearly match the task objectives

========================================

Change 1576926 by hjaltil@eve_branches_staging_2019-INCUBUS_hjaltil-pc on 2019/09/30 15:10:55

MapView is calling uicore.UpdateCursor(self, force=True) very often https://jira.ccpgames.com/browse/TQ-131671

* Removed unnecessary calls to uicore.UpdateCursor
* This was due to a legacy issue that has now been fixed, so there is no need for this patchwork anymore

QA: For repro steps see: https://jira.ccpgames.com/browse/EVEDEV-1285

========================================

Change 1576971 by camille@eve_branches_staging_2019-INCUBUS_camille-ws on 2019/09/30 15:55:01

INCUBUS round 01
DE/FR/RU
https://jira.ccpgames.com/browse/LSS-6594

========================================

Change 1577054 by javier@EVE_DEVELOPMENT_JAVIER-WS on 2019/09/30 16:36:58

Republishing TriGlavian Observatory and wreck for bug fixes.  Republishing the maetrialization controller for tweak/adjustment https://jira.ccpgames.com/browse/EVEDEV-8460 https://jira.ccpgames.com/browse/EVEDEV-8461 https://jira.ccpgames.com/browse/TC-111 https://jira.ccpgames.com/browse/TC-110

========================================

Change 1577141 by hjaltil@eve_branches_staging_2019-INCUBUS_hjaltil-pc on 2019/09/30 17:32:28

As a player, I know how to display Aura again after I've minimized her conversation window. https://jira.ccpgames.com/browse/PSYCHO-2093

* Added custom aura button to the neocom
* custom aura button blinks blue when created, with the same animation as all the other neocom buttons
* Removed theme color from custom aura button

========================================

Change 1577338 by arnarb@eve_branches_staging_2019-INCUBUS on 2019/10/01 10:29:56

Wallet: Balance not updating after giving/taking from Corporation Wallet until the user closes and reopens Wallet
https://jira.ccpgames.com/browse/EVEDEV-8476

- OnBalanceChange event now passes along the new balance instead of original balance. 
- Made sure the balance change pop-up accounts for those changes

========================================

Change 1577374 by arnarb@eve_branches_staging_2019-INCUBUS on 2019/10/01 10:46:28

Wallet: Market Orders tab does not blink and exception is thrown when it should
https://jira.ccpgames.com/browse/EVEDEV-8475

- Now handling case where there is no top-level tab group (no corp wallet)

========================================

Change 1577390 by chance@chance-pc on 2019/10/01 10:56:52

Correcting FSD errors in material set data for RRC

https://jira.ccpgames.com/browse/GFX-5888

========================================

Change 1577395 by arnarb@eve_branches_staging_2019-INCUBUS on 2019/10/01 11:05:55

Exception: 'CorpWalletContainer' object has no attribute 'iskLabel'
https://jira.ccpgames.com/browse/EVEDEV-8485

========================================

Change 1577401 by arnarb@eve_branches_staging_2019-INCUBUS on 2019/10/01 11:08:59

Exception: 'WalletWindow' object has no attribute 'maintabs'
https://jira.ccpgames.com/browse/EVEDEV-8483

========================================

Change 1577461 by hjaltil@eve_branches_staging_2019-INCUBUS_hjaltil-pc on 2019/10/01 11:41:21

As a player, I don't want to be able to collapse my current operation task in the info panel https://jira.ccpgames.com/browse/PSYCHO-2056

* Added a new attribute to mission info panel: "are_objectives_collapsable" and defaulted it to True for missions, but False for operations.
* Passing that attribute to the MissionEntry which uses that to determine if it should ever collapse itself or its sub objectives.

========================================

Change 1577485 by dylan@eve_branches_staging_2019-INCUBUS_dylan-ws on 2019/10/01 12:03:39

2019 Triglavian October - Stellar Fleet Dungeon - POLISH

- Changed the local messages in Incubus, because I made the initial change in the wrong workspace.

https://jira.ccpgames.com/browse/EVEDEV-8477

========================================

Change 1577538 by olivia@OLIVIA-WS on 2019/10/01 13:05:05

Addition of Stage B & C struts to Jita Holomass
--
https://jira.ccpgames.com/browse/TC-123

========================================

Change 1577619 by bara@eve_branches_staging_2019-INCUBUS_bara-pc on 2019/10/01 13:55:50

First Playable UI reward window
https://jira.ccpgames.com/browse/TFO-3201

 - adding a new icon for the claimed items
 - adding frame around all unclaimed items
 - adding a stronger frame around today's/next reward
 - adding countdown when displaying the next reward
 - adding back the browsing, and adding text that says 'reset' to go back to today's/next reward
 - add qty
 - changing the button so it becomes a 'close' button when nothing can be claimed

========================================

Change 1577620 by dylan@eve_branches_staging_2019-INCUBUS_dylan-ws on 2019/10/01 13:55:51

2019 Triglavian October - Stellar Fleet Dungeon - DEFECT

- For some reason, it was displaying both the new AND the old text. I believe this should now be fixed.

https://jira.ccpgames.com/browse/EVEDEV-8477

========================================

Change 1577782 by bara@eve_branches_staging_2019-INCUBUS_bara-pc on 2019/10/01 15:28:45

First Playable UI reward window
https://jira.ccpgames.com/browse/TFO-3201

 - updating the ui for the 'today's item' part
 - updating the tier names

========================================

Change 1577785 by joshua@joshua-ws on 2019/10/01 15:32:22

Republish for shipcontroller changes

https://jira.ccpgames.com/browse/TC-19

========================================

Change 1577786 by javier@EVE_DEVELOPMENT_JAVIER-WS on 2019/10/01 15:33:31

Republishing Observatory explosion file for .red file update https://jira.ccpgames.com/browse/TC-112

========================================

Change 1577817 by einarth@eve_branches_staging_2019-INCUBUS_einarth-pc on 2019/10/01 15:58:38

Trade not cancelled when undocking from station
https://jira.ccpgames.com/browse/EVEDEV-8469

Don't mark a session as dead before calling Abort() on it.

========================================

Change 1577889 by asgeir.arnason@ASGEIR-WS on 2019/10/01 16:41:34

NPE: The representation of shortcuts in Aura text is confusing
https://jira.ccpgames.com/browse/EVEDEV-8468 
https://jira.ccpgames.com/browse/PSYCHO-2112 
-Shortcuts are now explicit in their own dialogue line when possbile 
-Added instructions for using the second weapons along with shortcuts after having acquired them

========================================

Change 1577914 by eric@eric_MAINLINE_FOR_REAL on 2019/10/01 16:54:51

[eve 2019-INCUBUS][audio] Add ability to use StateTime() and Curve() in Tr2ActionBindRTPC expressions.
https://jira.ccpgames.com/browse/TC-10

========================================

Change 1577926 by einarth@eve_branches_staging_2019-INCUBUS_einarth-pc on 2019/10/01 16:58:53

Docked and undocked window states does not persist in Structures
https://jira.ccpgames.com/browse/EVEDEV-8457

Fallout from 'crazy pill' in CL 1560456 - no idea why I figured the scopes should be combined at that point, but this takes them back to being exclusive.

========================================

Change 1577932 by jamieb@eve_branches_staging_2019-INCUBUS_jamieb-ws on 2019/10/01 17:02:24

Implement: Auto-injecting ISK tokens that can be given out through the redeem queue
https://jira.ccpgames.com/browse/TFO-3288

If a user redeems a "Kredits" item (typeID 52996) then they will now receive an ISK payment to their wallet, where the ISK amount matches the quantity of the Kredits item in the redeem queue. The transaction in the wallet journal will be of a new type "refRedeemedISKToken = 147". The Kredits item itself should be removed from the redeem queue, and should NOT be created in any inventory.

EBS 8190

========================================

Change 1577958 by einarth@eve_branches_staging_2019-INCUBUS_einarth-pc on 2019/10/01 17:20:54

Structures: Undocking briefly shows non-friendly Citadels on overview
https://jira.ccpgames.com/browse/TQ-122815

Can't use bubbleIDs as early filter client-side as it's totally unaware of bubbleIDs.

========================================

Change 1577971 by einarth@eve_branches_staging_2019-INCUBUS_einarth-pc on 2019/10/01 17:25:03

Structures: Undocking briefly shows non-friendly Citadels on overview
https://jira.ccpgames.com/browse/TQ-122815

quick addendum to CL 1577958 - Remove variables that are unused after last change.

========================================

Change 1577979 by tormod@tormod_TORMOD-PC_1567 on 2019/10/01 17:31:30

Further fixes to Aura conversation messages

https://jira.ccpgames.com/browse/EVEDEV-8465

========================================

Change 1578029 by javier@EVE_DEVELOPMENT_JAVIER-WS on 2019/10/01 18:04:11

Republishing TriGlavian Observatory following review changes https://jira.ccpgames.com/browse/TC-8

========================================

Change 1578339 by chance@chance-pc on 2019/10/02 10:39:12

Golem Publish for Halloween 2019 Material Set adjustment

https://jira.ccpgames.com/browse/EVEDEV-8428

========================================

Change 1578370 by chance@chance-pc on 2019/10/02 11:01:11

Jita Holomass C - Strut republish for point lights

https://jira.ccpgames.com/browse/TC-123

========================================

Change 1578437 by hjaltil@eve_branches_staging_2019-INCUBUS_hjaltil-pc on 2019/10/02 11:33:54

NPE: Aura blink and highlight appear every time regardless of blink settings https://jira.ccpgames.com/browse/EVEDEV-8492

* Now checking if blinking is enabled before blinking the aura button
* Now checking a character settings attribute "hasSeenAuraHighlight" before showing the ui highlight, and setting it to True if they haven't seen it before, therefore never showing it again until the player resets their settings.

========================================

Change 1578478 by hjaltil@eve_branches_staging_2019-INCUBUS_hjaltil-pc on 2019/10/02 11:56:02

Back out changelist 1577461

[git-p4: depot-paths = "//eve/branches/development/MAINLINE/carbon/src/Trinity/": change = 1578594]